### ISSUE TITLE
Error: Dynamic require of "path" is not supported

### ISSUE THREAD

**Issue by extremelygooddeveloper** [Subwaytime/vite-aliases#33]
Hi, great work on this!

After updating from 0.8.7 to 0.9.1 i get the following error when building:

```
failed to load config from vite.config.js
error when starting dev server:
Error: Dynamic require of "path" is not supported
    at file:///src/webapp/node_modules/.pnpm/vite-aliases@0.9.1_sass@1.49.9/node_modules/vite-aliases/dist/index.mjs:30:9
    at node_modules/fast-glob/out/utils/path.js (file:///src/webapp/node_modules/.pnpm/vite-aliases@0.9.1_sass@1.49.9/node_modules/vite-aliases/dist/index.mjs:131:16)
    at __require2 (file:///src/webapp/node_modules/.pnpm/vite-aliases@0.9.1_sass@1.49.9/node_modules/vite-aliases/dist/index.mjs:36:50)
    at node_modules/fast-glob/out/utils/index.js (file:///src/webapp/node_modules/.pnpm/vite-aliases@0.9.1_sass@1.49.9/node_modules/vite-aliases/dist/index.mjs:3235:16)
    at __require2 (file:///src/webapp/node_modules/.pnpm/vite-aliases@0.9.1_sass@1.49.9/node_modules/vite-aliases/dist/index.mjs:36:50)
    at node_modules/fast-glob/out/managers/tasks.js (file:///src/webapp/node_modules/.pnpm/vite-aliases@0.9.1_sass@1.49.9/node_modules/vite-aliases/dist/index.mjs:3253:17)
    at __require2 (file:///src/webapp/node_modules/.pnpm/vite-aliases@0.9.1_sass@1.49.9/node_modules/vite-aliases/dist/index.mjs:36:50)
    at node_modules/fast-glob/out/index.js (file:///src/webapp/node_modules/.pnpm/vite-aliases@0.9.1_sass@1.49.9/node_modules/vite-aliases/dist/index.mjs:5167:23)
    at __require2 (file:///src/webapp/node_modules/.pnpm/vite-aliases@0.9.1_sass@1.49.9/node_modules/vite-aliases/dist/index.mjs:36:50)
    at file:///src/webapp/node_modules/.pnpm/vite-aliases@0.9.1_sass@1.49.9/node_modules/vite-aliases/dist/index.mjs:5240:32
 ELIFECYCLE  Command failed with exit code 1.
```

working: [working.zip](https://github.com/Subwaytime/vite-aliases/files/8223560/working.zip)
repro: [repro.zip](https://github.com/Subwaytime/vite-aliases/files/8226420/new-repro.zip)

using versions
vite: 2.8.6
node: v17.1.0
pnpm: 6.23.2
npm: 8.1.2

**Comment by Subwaytime** [comment]
Hey thanks for reporting this!
Will take a look later today what could cause this 🤔

**Comment by Subwaytime** [comment]
@ivarlovlie Would you be able to provide a reproduction?
Also it would be good to know what node version you are using. 
Ive tried to replicate the issue with `node 16`, `npm 8` and vite 2.8.6 and dont run into the same Issue!

**Comment by ivarlovlie** [comment]
Attached is one bare-bones vite project with a simple import that works as expected, and one copy of the project where i am seeing the regression. I am able to build the repro project when i'm on 0.8.7 of vite-aliases, and unable on 0.9.1.

working: [working.zip](https://github.com/Subwaytime/vite-aliases/files/8223560/working.zip)
repro: [repro.zip](https://github.com/Subwaytime/vite-aliases/files/8223562/repro.zip)

**Comment by Subwaytime** [comment]
I did a test reproduction in this git repo here:
https://github.com/Subwaytime/vite-aliases-test

It works flawlessly for me, even tried pnpm.

used pnpm: 6.32.3 (latest)

Cant seem to replicate your Issue. What operating system do you use?

**Comment by ivarlovlie** [comment]
I am using Ubuntu 20.04
Tried with node 16.14.0 but still see the same behaviour using vite-aliases 0.9.1.

> Cant seem to replicate your Issue

You're not able to reproduce on the project inside of repro.zip?

**Comment by ivarlovlie** [comment]
After further troubleshooting i managed to build with 0.9.1 by remove `type: "module"` from package.json. Would it be worth looking into why `type: "module"` worked with 0.8.7 but not with 0.9.1?.

**Comment by Subwaytime** [comment]
Yeah so the type in package forces the build/dev to be in esm rather then cjs. I am checking now whether this is due to vite-aliases or a change in fast-glob, as this is reporting the error.

**Comment by Subwaytime** [comment]
esm is technically still experimental on nodejs 16+, so you might run into troubles with this anyways. normally its not recommended, i will see if i can get vite-aliases to support it, or atleast find a work around if fast-glob is causing the issue.

**Comment by jcoble** [comment]
Just wanted to say I was getting the same error.  Tried going down to 16.14.2 and that didn't help.  Was on 9.1 but upgraded to 9.2.  Is this then resolved?  Below was the error I was getting if it were to be any help if it's not resolved.


error when starting dev server:
Error: Dynamic require of "path" is not supported
    at file:///Users/jessecoble/Repositories/PLAYGROUND/SvelteTemplate/SvelteTemplate/node_modules/vite-aliases/dist/index.mjs:30:9
    at node_modules/fast-glob/out/utils/path.js (file:///Users/jessecoble/Repositories/PLAYGROUND/SvelteTemplate/SvelteTemplate/node_modules/vite-aliases/dist/index.mjs:131:16)
    at __require2 (file:///Users/jessecoble/Repositories/PLAYGROUND/SvelteTemplate/SvelteTemplate/node_modules/vite-aliases/dist/index.mjs:36:50)
    at node_modules/fast-glob/out/utils/index.js (file:///Users/jessecoble/Repositories/PLAYGROUND/SvelteTemplate/SvelteTemplate/node_modules/vite-aliases/dist/index.mjs:3235:16)
    at __require2 (file:///Users/jessecoble/Repositories/PLAYGROUND/SvelteTemplate/SvelteTemplate/node_modules/vite-aliases/dist/index.mjs:36:50)
    at node_modules/fast-glob/out/managers/tasks.js (file:///Users/jessecoble/Repositories/PLAYGROUND/SvelteTemplate/SvelteTemplate/node_modules/vite-aliases/dist/index.mjs:3253:17)
    at __require2 (file:///Users/jessecoble/Repositories/PLAYGROUND/SvelteTemplate/SvelteTemplate/node_modules/vite-aliases/dist/index.mjs:36:50)
    at node_modules/fast-glob/out/index.js (file:///Users/jessecoble/Repositories/PLAYGROUND/SvelteTemplate/SvelteTemplate/node_modules/vite-aliases/dist/index.mjs:5167:23)
    at __require2 (file:///Users/jessecoble/Repositories/PLAYGROUND/SvelteTemplate/SvelteTemplate/node_modules/vite-aliases/dist/index.mjs:36:50)
    at file:///Users/jessecoble/Repositories/PLAYGROUND/SvelteTemplate/SvelteTemplate/node_modules/vite-aliases/dist/index.mjs:5240:32

**Comment by jcoble** [comment]
I'm sorry, i actually downgraded to 8.6 of vite-aliases and that worked.  I thought that's what I did but my package.json was showing 9.2 for some reason.  I stopped and tried to restart the dev server and got the error again.  Tried downgrading to 8.6 again, this time it "took" and showed as 8.6 in package.json and was then able to start the dev server.  Sorry for the confusion.

**Comment by Subwaytime** [comment]
Hmm thats interesting, are you using `"type":"module"` in your package.json too? or without it?

**Comment by jcoble** [comment]
Ya. I tried taking it out and just got a bunch more errors. I don't know a whole lot about bundlers, config files etc. Just been learning more about them, especially Vite. There's something special about it that just really intrigues me. I guess its just the pure speed of it and how it can build 100x faster than other bundlers. Anyways, if you need anymore info let me know. Be happy to help.

**Comment by Tommertom** [comment]
+1 this issue - node v16.14.2,  with type=module 
Thx for the project though!

**Comment by Subwaytime** [comment]
fix is coming with the newest release!

**Comment by Subwaytime** [comment]
quick note: due to covid i wasnt able to work on this again, but now i can finally continue!

also, i will bundle this with the upcoming major changes from vite 3!

**Comment by Aurorxa** [comment]
https://vitejs.dev/guide/build.html#library-mode

![image](https://user-images.githubusercontent.com/25677587/187816905-6a6f8091-5abf-49c4-81db-4dcc5d55aef6.png)

**Comment by Subwaytime** [comment]
@Aurorxa thanks for that link, i have already updated these according to the docs, there are just some other bugs that currently interfere with a release

**Comment by MattMarquise** [comment]
@Subwaytime I had this same issue recently with new Vite project and removing "type": "module" fixed the issue.

**Comment by binulad** [comment]
Add the below code in the **'vite.config.ts'** or **'vite.config.js'** file:

import { resolve } from 'path';

export default defineConfig({
  resolve: {
    alias: {
      '@': resolve(__dirname, './src')
    },
  },
  plugins: [vue()],
})

**Comment by MoySantanaV** [comment]
in my case I just change

**Comment by MoySantanaV** [comment]
In my case I just change 
`const path = require('path')` to
`const path = require('path')` and works.

**Comment by izetter** [comment]
@Subwaytime Is there still a planned fix so "type": "module" doesn't have to be removed from package.json?

**Comment by thuyduongbka** [comment]
if package.json
`"type": "module",`
then vite.config.js
`import path from 'path';`

**Comment by arunkmoury** [comment]
> if package.json `"type": "module",` then vite.config.js `import path from 'path';`

this solution works with node v20.8.0
