### ISSUE TITLE
Vite-plugin-pwa dynamic require of workbox-build issue occurring only on Vercel builds

### ISSUE THREAD

**Issue by OrzMiku** [Subwaytime/vite-aliases#70]
```
10:17:29.543 | Error: Dynamic require of "workbox-build" is not supported
10:17:29.543 | at file:///vercel/path0/node_modules/vite-plugin-pwa/dist/index.js:6:9
10:17:29.543 | at loadWorkboxBuild (file:///vercel/path0/node_modules/vite-plugin-pwa/dist/index.js:268:12)
10:17:29.543 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:17:29.544 | at async generateServiceWorker (file:///vercel/path0/node_modules/vite-plugin-pwa/dist/index.js:301:26)
10:17:29.544 | at async _generateSW (file:///vercel/path0/node_modules/vite-plugin-pwa/dist/index.js:471:5)
10:17:29.544 | at async Object.handler (file:///vercel/path0/node_modules/vite-plugin-pwa/dist/index.js:602:11)
10:17:29.544 | at async PluginDriver.hookParallel (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:25466:17)
10:17:29.544 | at async Object.close (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:26726:13)
10:17:29.544 | at async build (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48095:13)
10:17:29.544 | at async CAC.<anonymous> (file:///vercel/path0/node_modules/vite/dist/node/cli.js:842:9)
10:17:29.564 | error: script "build" exited with code 1 (SIGHUP)
10:17:29.567 | Error: Command "bun run build" exited with 1
```

**Comment by OrzMiku** [comment]
Sorry, ISSUE should be submitted to another repository
